sudo: false

language: c

matrix:
  include:
    - env: BUILD=stack GHCVER=7.10.3 STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=stack GHCVER=7.10.3 STACK_YAML=stack-5.yaml
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3 osx"
      os: osx
    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-8.0.2,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
  - ./.travis-setup.sh
  - ghc --version || stack exec -- ghc --version
  - happy --version || true
  - cabal --version || true
  - stack --version || true
  - tick --version || true

install:
  - case "$BUILD" in
      stack)
        stack --no-terminal test --only-dependencies;;
    esac

script:
  - case "$BUILD" in
      stack)
        stack --no-terminal test --haddock --no-haddock-deps;;
    esac

cache:
  directories:
    - $HOME/.stack
