name: cabalize

dependencies:
  - aeson
  - base == 4.*
  - base-compat
  - directory
  - filepath
  - interpolate
  - unordered-containers
  - yaml

tests:
  spec:
    main: test/Spec.hs
    dependencies:
      - hspec == 2.*
      - temporary
