name: cabalize
license: MIT

ghc-options: -Wall

dependencies:
  - aeson >= 0.8
  - base == 4.*
  - base-compat
  - directory
  - filepath
  - interpolate
  - unordered-containers
  - yaml

library:
  exposed-modules:
    - Cabalize

executables:
  cb:
    main: driver/Main.hs
    dependencies: cabalize

tests:
  spec:
    main: test/Spec.hs
    dependencies:
      - hspec == 2.*
      - temporary
