name: cabalize
license: MIT
github: sol/cabalize

ghc-options: -Wall

dependencies:
  - aeson >= 0.8
  - base == 4.*
  - base-compat >= 0.7
  - directory
  - filepath
  - interpolate
  - unordered-containers
  - yaml

library:
  exposed-modules:
    - Cabalize

executables:
  cb:
    main: driver/Main.hs
    dependencies: cabalize

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - temporary
